CREATE DATABASE USER COLLATE "UTF8_GENERAL_CI"
CREATE TABLE USERS (
    ID INT(4) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50)
);

-- INSERTAR USER
CREATE PROCEDURE `spInsertUser`(IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN INSERT INTO USERS (NAME) VALUES (_NAME); END;

-- CALL spInsertUser('becerra');

-- MOSTRAR TODOS LOS USER
CREATE PROCEDURE `spFindAllUser`() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN SELECT ID,NAME FROM USERS; END;

-- CALL spFindAllUser();

-- MOSTRAR UN SOLO USER
CREATE PROCEDURE `spFindUser`(IN `_ID` INT(5)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN SELECT ID,NAME FROM USERS WHERE ID = _ID; END:

-- ACTUALIZAR
CREATE PROCEDURE `spUpdateUser`(IN `_ID` INT, IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN UPDATE USERS SET NAME = _NAME WHERE ID = _ID; END;

-- ELIMINAR 
CREATE PROCEDURE `spDeleteUser`(IN `_ID` INT(5)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN DELETE FROM USERS WHERE ID = _ID; END;